trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: true
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  inputs:
    PathtoPublish: dist
    ArtifactName: app

